from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from app.llm_gate import ask_medical_llm
from app.publisher import publish_to_webplatform
from validator.response_validator import validate_llm_response
from validator.validator_logs import log_validation_attempt

router = APIRouter()


class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="Question generated by the Trad LLM from the patient conversation.",
        examples=["Patient reports sharp chest pain radiating to the left arm for 20 minutes."],
    )
    appointment_id: str = Field(
        ...,
        min_length=1,
        description="Appointment UUID that the resulting Note or Suggestion belongs to.",
        examples=["cccc0000-0000-0000-0000-000000000001"],
    )


class AskResponse(BaseModel):
    response: str = Field(
        description="Validated Note or Suggestion content from the medical LLM."
    )
    kind: str | None = Field(
        default=None,
        description="'Note' or 'Suggestion' when the response was successfully validated.",
    )
    published: bool = Field(
        default=False,
        description="Whether the message was successfully written to the webPlatform DB.",
    )


@router.post(
    "/ask",
    response_model=AskResponse,
    summary="Send a question to the medical LLM",
    description=(
        "Accepts a question from the Trad LLM, forwards it to the medical LLM "
        "with the clinical system prompt, validates the response, and publishes "
        "the validated Note or Suggestion to the webPlatform DB."
    ),
)
async def ask(body: AskRequest) -> AskResponse:
    result = ""
    try:
        attempt_number = 1

        while attempt_number < 4:
            result = await ask_medical_llm(body.question)

            parsed_result = validate_llm_response(result)

            log_validation_attempt(attempt_number, parsed_result)

            if parsed_result.is_valid:
                published = await publish_to_webplatform(
                    parsed_result.kind,
                    parsed_result.msg,
                    body.appointment_id,
                )
                return AskResponse(
                    response=parsed_result.msg,
                    kind=parsed_result.kind,
                    published=published,
                )

            attempt_number += 1

        print("Failed to parse the llm after 3 attempts")

    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Ollama unreachable or returned an unexpected error: {exc}",
        )

    return AskResponse(response=result, kind=None, published=False)
